version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Etc/Greenwich
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Etc/Greenwich
