source "https://rubygems.org/"

gem "productive", "~> 0.6.66"
gem "dotenv"
gem "rspec"
gem "pry"
gem "standard"
gem "webmock"
gem "timecop"
gem "rake"
gem "factory_bot"
gem "ffaker"
gem "climate_control"
