name: Run
env:
  PRODUCTIVE_ACCOUNT_ID: ${{ secrets.PRODUCTIVE_ACCOUNT_ID }}
  PRODUCTIVE_API_KEY: ${{ secrets.PRODUCTIVE_API_KEY }}
  SUPPORT_PROJECT_ID: ${{ secrets.SUPPORT_PROJECT_ID }}
  SUPPORT_SERVICE_ID: ${{ secrets.SUPPORT_SERVICE_ID }}
  SUPPORT_ROTA_API_URI: https://dxw-support-rota.herokuapp.com
  IMPORT_DEV_IN_HOURS: true
  IMPORT_OPS_IN_HOURS: true

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Import
        id: import
        run: |
          bundle exec rake support_rota_to_productive:import:dry_run && \
          bundle exec rake support_rota_to_productive:import:run
